
CREATE TABLE TASK (
  TASK_ID     VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255),
  DONE        BOOLEAN,
  TIMESTAMP   TIMESTAMP,
  TITLE       VARCHAR(255),
  USER_ID     VARCHAR(255),
  PRIMARY KEY (TASK_ID)
);
