
INSERT INTO TASK (TASK_ID, USER_ID, TIMESTAMP, TITLE, DESCRIPTION, DONE) 
  SELECT UUID(), 'guest', CURRENT_TIMESTAMP(), 'Steuererklaerung machen', NULL, TRUE;

INSERT INTO TASK (TASK_ID, USER_ID, TIMESTAMP, TITLE, DESCRIPTION, DONE) 
  SELECT UUID(), 'guest', CURRENT_TIMESTAMP(), 'Einkaufen fuers Wocheende', 'Brot, Milch, Kaese, Wein', FALSE;

INSERT INTO TASK (TASK_ID, USER_ID, TIMESTAMP, TITLE, DESCRIPTION, DONE) 
  SELECT UUID(), 'guest', CURRENT_TIMESTAMP(), 'Docker fuer Quarkus nochmals anschauen', NULL, NULL;
